#! /usr/bin/env php

<?php

use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$app = new Application('Dominoes', '1.0');

$app->add(new Domino\StartCommand());

$app->run();
